# Generated by Django 4.1.7 on 2023-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
